typeidea/typeidea/urls.py
from django.contrib import admin
from django.urls import path
from django.contrib.sitemaps import views as sitemap_views
from django.conf.urls import url
# from blog.views import post_list, post_detail, links
from blog.views import links
from blog.views import PostDetailView, PostListView, CategoryView, \
    TagView, SearchView, AuthorView, LinkListView, CommentView
from blog.rss import LatestPostFeed
from blog.sitemap import PostSitemap

# urlpatterns = [
#     path('admin/', admin.site.urls),
# ]

urlpatterns = [
    # url(r'^$', post_list, name='index'),
    url(r'^$', PostListView.as_view(), name='index'),
    url(r'^search/$', SearchView.as_view(), name='search'),
    url(r'^author/(?P<owner_id>\d+)/$', AuthorView.as_view(), name='author'),
    # url(r'^category/(?P<category_id>\d+)/$', post_list, name='category-list'),
    url(r'^category/(?P<category_id>\d+)/$', CategoryView.as_view(), name='category-list'),
    # url(r'^tag/(?P<tag_id>\d+)/$', post_list, name='tag-list'),
    url(r'^tag/(?P<tag_id>\d+)/$', TagView.as_view(), name='tag-list'),
    # url(r'^post/(?P<post_id>\d+).html$', post_detail, name='post-detail'),
    url(r'^post/(?P<post_id>\d+).html$', PostDetailView.as_view(), name='post-detail'),
    # url(r'^links/$', links, name='links'),
    url(r'^links/$', LinkListView.as_view(), name='links'),
    url(r'^comment/$', CommentView.as_view(), name='comment'),
    url(r'^rss|feed/', LatestPostFeed(), name='rss'),
    url(r'^sitemap\.xml$', sitemap_views.sitemap, {'sitemaps': {'posts': PostSitemap}}),
    url(r'^admin/', admin.site.urls, name='admin'),
]

typeidea/blog/models.py
from django.db import models
from django.contrib.auth.models import User
from django.template.loader import render_to_string
from django.utils.functional import cached_property
import mistune


class Tag(models.Model):
    # 标签
    STATUS_NORMAL = 1
    STATUS_DELETE = 0
    STATUS_ITEMS = (
        (STATUS_NORMAL, '正常'),
        (STATUS_DELETE, '删除'),
    )

    name = models.CharField(max_length=10, verbose_name='名称')
    status = models.PositiveIntegerField(default=STATUS_NORMAL, choices=STATUS_ITEMS, verbose_name='状态')
    owner = models.ForeignKey(User, verbose_name='作者', on_delete=models.SET_NULL, blank=True, null=True)
    created_time = models.DateTimeField(auto_now_add=True, verbose_name='创建时间')

    def __str__(self):
        return self.name

    # 侧边栏
    @classmethod
    def get_all(cls):
        return cls.objects.filter(status=Tag.STATUS_NORMAL)

    class Meta:
        verbose_name = verbose_name_plural = '标签'


class Category(models.Model):
    # 分类
    STATUS_NORMAL = 1
    STATUS_DELETE = 0
    STATUS_ITEMS = (
        (STATUS_NORMAL, '正常'),
        (STATUS_DELETE, '删除'),
    )

    name = models.CharField(max_length=50, verbose_name='名称')
    status = models.PositiveIntegerField(default=STATUS_NORMAL, choices=STATUS_ITEMS, verbose_name='状态')
    is_nav = models.BooleanField(default=False, verbose_name='是否为导航')
    owner = models.ForeignKey(User, verbose_name='作者', on_delete=models.SET_NULL, blank=True, null=True)
    created_time = models.DateTimeField(auto_now_add=True, verbose_name='创建时间')

    def __str__(self):
        return self.name

    @classmethod
    def get_navs(cls):
        # 获取分类列表和标记为导航的分类列表
        categories = cls.objects.filter(status=Category.STATUS_NORMAL)
        nav_categories = []
        normal_categories = []
        for cate in categories:
            if cate.is_nav:
                nav_categories.append(cate)
            else:
                normal_categories.append(cate)
        return {'navs': nav_categories, 'categories': normal_categories, }

    class Meta:
        verbose_name = verbose_name_plural = '分类'


class Post(models.Model):
    # 文章
    STATUS_NORMAL = 1
    STATUS_DELETE = 0
    STATUS_DRAFT = 2
    STATUS_ITEMS = (
        (STATUS_NORMAL, '正常'),
        (STATUS_DELETE, '删除'),
        (STATUS_DRAFT, '草稿')
    )

    title = models.CharField(max_length=255, verbose_name='标题')
    desc = models.CharField(max_length=1024, blank=True, verbose_name='摘要')
    content = models.TextField(verbose_name='正文', help_text='正文必须为MarkDown格式')
    content_html = models.TextField(verbose_name='正文HTML代码', default='', help_text='正文必须为MarkDown格式')
    status = models.PositiveIntegerField(default=STATUS_NORMAL, choices=STATUS_ITEMS, verbose_name='状态')
    category = models.ForeignKey(Category, verbose_name='分类', on_delete=models.SET_NULL, blank=True, null=True)
    tag = models.ManyToManyField(Tag, verbose_name='标签')
    owner = models.ForeignKey(User, verbose_name='作者', on_delete=models.SET_NULL, blank=True, null=True)
    created_time = models.DateTimeField(auto_now_add=True, verbose_name='创建时间')

    pv = models.PositiveIntegerField(default=1)   # 浏览量点击量
    uv = models.PositiveIntegerField(default=1)   # 独立访客

    def __str__(self):
        return self.title

    @staticmethod
    def get_by_tag(tag_id):
        # 根据标签获取文章列表
        try:
            tag = Tag.objects.get(id=tag_id)
        except Tag.DoesNotExist:
            tag = None
            post_list = []
        else:
            post_list = tag.post_set.filter(status=Post.STATUS_NORMAL).select_related('owner', 'category')
        return post_list, tag

    @staticmethod
    def get_by_category(category_id):
        try:
            category = Category.objects.get(id=category_id)
        except Category.DoesNotExist:
            category=None
            post_list = []
        else:
            post_list = category.post_set.filter(status=Post.STATUS_NORMAL).select_related('owner', 'category')
        return post_list, category

    @classmethod
    def get_all(cls):
        # 所有帖子
        return cls.objects.filter(status=cls.STATUS_NORMAL)

    @classmethod
    def latest_posts(cls):
        # 最新帖子
        queryset = cls.objects.filter(status=cls.STATUS_NORMAL)
        return queryset[:3]

    @classmethod
    def get_by_id(cls, id):
        queryset = cls.objects.filter(pk=id)
        return queryset

    @classmethod
    def hot_posts(cls):
        return cls.objects.filter(status=cls.STATUS_NORMAL).order_by('-pv')

    def save(self, *args, **kwargs):
        # 重写保存函数，将Content转为Markdown格式保存
        self.content_html = mistune.markdown(self.content)
        return super().save(*args, **kwargs)

    @cached_property
    def tags(self):
        return ','.join(self.tag.values_list('name', flat=True))

    class Meta:
        verbose_name = verbose_name_plural = '文章'
        ordering = ['-id']    # 根据id降序排列


class Comment(models.Model):
    # 评论
    STATUS_NORMAL = 1
    STATUS_DELETE = 0
    STATUS_ITEMS = (
        (STATUS_NORMAL, '正常'),
        (STATUS_DELETE, '删除'),
    )

    target = models.ForeignKey(Post, verbose_name='评论目标', on_delete=models.SET_NULL, blank=True, null=True)
    content = models.CharField(max_length=2000, verbose_name='内容')
    nickname = models.CharField(max_length=50, verbose_name='昵称')
    website = models.URLField(verbose_name='网站')
    email = models.EmailField(verbose_name='邮箱')
    owner = models.ForeignKey(User, verbose_name='作者', on_delete=models.SET_NULL, blank=True, null=True)
    status = models.PositiveIntegerField(default=STATUS_NORMAL, choices=STATUS_ITEMS, verbose_name='状态')
    created_time = models.DateTimeField(auto_now_add=True, verbose_name='创建时间')

    def __str__(self):
        return self.content

    def save(self, *args, **kwargs):
        # 重写保存函数，将Content转为Markdown格式保存
        self.owner = User.objects.get(username='root')
        return super().save(*args, **kwargs)

    @classmethod
    def get_by_target(cls, target):
        return cls.objects.filter(target=target, status=cls.STATUS_NORMAL)

    class Meta:
        verbose_name = verbose_name_plural = '评论'

class Link(models.Model):
    # 友链
    STATUS_NORMAL = 1
    STATUS_DELETE = 0
    STATUS_ITEMS = (
        (STATUS_NORMAL, '正常'),
        (STATUS_DELETE, '删除'),
    )

    title = models.CharField(max_length=50, verbose_name='标题')
    href = models.URLField(verbose_name='链接')
    status = models.PositiveIntegerField(default=STATUS_NORMAL, choices=STATUS_ITEMS, verbose_name='状态')
    weight = models.PositiveIntegerField(default=1, choices=zip(range(1, 6), range(1, 6)),
                                         verbose_name='权重', help_text='权重高排名靠前')
    owner = models.ForeignKey(User, verbose_name='作者', on_delete=models.SET_NULL, blank=True, null=True)
    created_time = models.DateTimeField(auto_now_add=True, verbose_name='创建时间')

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = verbose_name_plural = '友链'


class SideBar(models.Model):
    """侧边栏"""
    STATUS_SHOW = 0
    STATUS_HIDE = 1
    STATUS_ITEM = (
        (STATUS_SHOW, '显示'),
        (STATUS_HIDE, '隐藏'),
    )

    DISPLAY_HTML = 1
    DISPLAY_LATEST = 2
    DISPLAY_HOT = 3
    DISPLAY_COMMENT = 4
    SIDE_TYPE = (
        (DISPLAY_HTML, 'HTML'),
        (DISPLAY_LATEST, '最新文章'),
        (DISPLAY_HOT, '最热文章'),
        (DISPLAY_COMMENT, '最近评论'),
    )

    """字段"""
    title = models.CharField(max_length=50, verbose_name='标题')
    display_type = models.PositiveIntegerField(verbose_name='显示类型', default=1, choices=SIDE_TYPE)
    content = models.CharField(max_length=500, blank=True, verbose_name='内容', help_text='如果设置的不是HTML类型，可为空')
    status = models.PositiveIntegerField(default=STATUS_SHOW, choices=STATUS_ITEM, verbose_name='状态')
    owner = models.ForeignKey(User, verbose_name='作者', on_delete=models.SET_NULL, blank=True, null=True)
    created_time = models.DateTimeField(auto_now_add=True, verbose_name='创建时间')

    class Meta:
        verbose_name = verbose_name_plural = '侧边栏'

    def __str__(self):
        return self.title

    @classmethod
    def get_all(cls):
        return cls.objects.filter(status=cls.STATUS_SHOW)

    @property
    def content_html(self):
        """返回HTML格式字符串"""
        result = ''
        if self.display_type == self.DISPLAY_HTML:
            # 侧边栏类型为HTML
            result = self.content
        elif self.display_type == self.DISPLAY_LATEST:
            # 侧边栏类型为最新文章
            context = {'posts': Post.latest_posts()}
            result = render_to_string('blocks/sidebar_posts.html', context)        # 返回最新文章列表
        elif self.display_type == self.DISPLAY_HOT:
            # 侧边栏类型为最热文章
            context = {'posts': Post.hot_posts()}
            result = render_to_string('blocks/sidebar_posts.html', context)       # 返回最最热章列表
        elif self.display_type == self.DISPLAY_COMMENT:
            # 侧边栏类型为最近评论
            context = {
                'comments': Comment.objects.filter(status=Comment.STATUS_NORMAL)
            }
            result = render_to_string('blocks/sidebar_comments.html', context)       # 返回最近评论列表

        return result

typeidea/blog/forms.py
from django import forms
from .models import Comment
import mistune

"""
表单用来定义需要提交的内容和格式
"""


class CommentForm(forms.ModelForm):
    nickname = forms.CharField(
        label='昵称',
        max_length=50,
        widget=forms.widgets.Input(
            attrs={'class': 'form-control', 'style': "width: 60%;"}
        )
    )
    email = forms.CharField(
        label='Email',
        max_length=50,
        widget=forms.widgets.EmailInput(
            attrs={'class': 'form-control', 'style': "width: 60%;"}
        )
    )
    website = forms.CharField(
        label='网站',
        max_length=100,
        widget=forms.widgets.URLInput(
            attrs={'class': 'form-control', 'style': "width: 60%;"}
        )
    )
    content = forms.CharField(
        label='内容',
        max_length=500,
        widget=forms.widgets.Textarea(
            # attrs={'rows': 6, 'cols': 60, 'class': 'form-control'}
            attrs={'class': 'form-control', 'style': "width: 60%;"}
        )
    )

    def clean_content(self):
        # 自定义数据校验
        content = self.cleaned_data.get('content')
        if len(content) < 10:
            raise forms.ValidationError('内容长度不能少于10个字符！')
        content = mistune.markdown(content)
        return content

    def as_p(self):
        "重写as_p"
        return self._html_output(
            normal_row='<p%(html_class_attr)s>%(label)s  %(field)s %(help_text)s</p>',
            error_row='%s',
            row_ender='</p>',
            help_text_html=' <span class="helptext">%s</span>',
            errors_on_separate_row=True,
        )

    class Meta:
        model = Comment   # 绑定数据
        fields = ['nickname', 'email', 'website', 'content']  # 显示的字段

typeidea/themes/bootstrap/templates/blog/base-bk.html
<!DOCTYPE html>
<html lang="zh-cn">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}首页{% endblock %}-typeidea 博客系统</title>
</head>
<body>
<!-- 导航 -->
<div>顶部导航：
    {% for cate in navs %}
    <a href="{% url 'category-list' cate.id %}">{{ cate.name }}</a>
    {% endfor %}
</div>
<hr/>

{% block main %}
{% endblock %}
<hr/>

<!-- 导航 -->
<div>底部导航：
    {% for cate in categories %}
    <a href="{% url 'category-list' cate.id %}">{{ cate.name }}</a>
    {% endfor %}
</div>
<hr/>

<!-- 侧边栏 -->
<div>侧边栏：
    {% for sidebar in sidebars %}
        <h4>{{ sidebar.title }}</h4>
        <!-- 调用封装好的sidebar -->
        {{ sidebar.content_html }}
    {% endfor %}
</div>


</body>
</html>

typeidea/themes/bootstrap/templates/blog/base.html
<!DOCTYPE HTML>
<html lang="en">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <title>{% block title %}首页{% endblock %}-typeidea 博客系统</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<!--    <link rel="stylesheet" href="https://cdn.bootcss.com/bootstrap/4.0.0/css/bootstrap.css">-->
    <link href="{% static 'css/bootstrap.css' %}" rel="stylesheet" >
    <link href="{% static 'css/my.css' %}" rel="stylesheet">
</head>
<body>
<!-- 导航 -->
<div class="container head">
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="/">首页</a>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                {% for cate in navs %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'category-list' cate.id %}">{{ cate.name }}</a>
                </li>
                {% endfor %}
                {{ request.path }}
            </ul>
        </div>
        <div>
            <form class="form-inline my-2 my-1g-0" action="/search/" method="GET">
                <input class="form-control mr-sm-2" type="search" name="keyword" placeholder="Search"
                       aria-label="Search" value="{{ keyword }}">
                <button class="btn btn-outline-success" type="submit">搜索</button>
            </form>
        </div>
    </nav>
    <div class="jumbotron">
        <h1 class="display-4">Typeidea</h1>
        <p class="lead">基于Django的多人博客系统</p>
    </div>
</div>

<!-- 博客区域 -->
<div class="container main">
    <div class="row">
        <div class="col-9 post-list">
            {% block main %}
            {% endblock %}
        </div>
        <!-- 侧边栏 -->
        <div class="col-3">
            {% block sidebar %}

                {% for sidebar in sidebars %}
                    <div class="card sidebars">
                        <div class="card-body">
                            <h4 class="card-title">{{ sidebar.title }}</h4>
                            <p>
                                <!--生成侧边栏HTML字符串-->
                                {{ sidebar.content_html }}
                            </p>
                        </div>
                    </div>
                {% endfor %}

            <div class="card sidebars">
                <div class="card-body">
                    <h4 class="card-title">分类</h4>
                    {% for cate in categories %}
                        <a class="nav-link" href="{% url 'category-list' cate.id %}">{{ cate.name }}</a>
                    {% endfor %}
                </div>
            </div>
            {% endblock %}
        </div>
    </div>
</div>
<hr/>

<!-- 底部导航 -->
<footer class="footer">
    {% block footer %}
    <div class="container power">
        <span class="text-muted">Power by Eric.kun</span>
    </div>
    {% endblock %}
</footer>
</body>
</html>

typeidea/themes/bootstrap/templates/blog/clsDetail.html
{% if post %}
<h1>{{ post.title }}</h1>
<div>
    <span>分类：{{ post.category.name }}</span>
    <span>作者：{{ post.owner.username }}</span>
</div>
{% if post.content_html %}
    {% autoescape off %}
    <p>{{ post.content_html }}</p>
    {% endautoescape %}
{% else %}
    <p>{{ post.content }}</p>
{% endif %}
{% endif %}

<hr/>

<div class="comment">
    <form class="form-group" action="/comment/" method="POST">
        {% csrf_token %}
        <input name="target" type="hidden" value="{{ request.path }}" />
        <input name="post_id" type="hidden" value="{{ post.id }}" />
        {{ comment_form.as_p }}
        <input type="submit" value="写好了!" />
    </form>

    <!-- 评论列表 -->
    <ul class="list-group">
        {% for comment in comment_list %}
        <li class="list-group-item">
            <div class="nickname">
                <a href="{{ comment.website }}">{{ comment.nickname }}</a>
                <span>{{ comment.created_time }}</span>
            </div>
            <div class="comment-content">
                {% autoescape off %}
                {{ comment.content }}
                {% endautoescape %}
            </div>
        </li>
        {% endfor %}
    </ul>
</div>

typeidea/themes/bootstrap/templates/blog/clslist.html
{% extends "./base.html" %}


{% block title %}
    {% if tag %}
    <!-- 标签页：{{ tag.name }} -->
    标签页：{{ sidebars }}
    {% elif category %}
    分类页：{{ category.naame }}
    {% endif %}
{% endblock%}

{% block main %}
<!--<ul>-->
    {% for post in post_list %}
    <div class="card post">
        <div class="card-body">
            <h5 class="card-title">
                <!-- <a href="/post/{{ post.id }}.html">{{ post.title }}</a> -->
                <h3><a href="{% url 'post-detail' post.id%}">{{ post.title }}</a></h3>
                <p>
                <span class="card-link">作者：<a href="{% url 'author' post.owner.id %}">{{ post.owner.username }}</a></span>
                <span class="card-link">分类：<a href="{% url 'category-list' post.category.id %}">{{ post.category.name }}</a></span>
                <span class="card-link">标签：
                    {% for tag in post.tag.all %}
                        <a href="{% url 'tag-list' tag.id %}">{{ tag.name }}</a>
                    {% endfor %}
                </span>
                </p>
                <p class="card-text">{{ post.desc }}
                    <a href="{% url 'post-detail' post.id %}">完整内容</a>
                </p>
            </h5>
        </div>
    </div>
    {% endfor %}
    <!-- 分页栏 -->
    <div>
    {% if page_obj %}
        {% if page_obj.has_previous %}
            <a href="?page={{ page_obj.previous_page_number }}">上一页</a>
        {% endif %}
        Page {{ page_obj.number }} of {{ paginator.num_pages }}.
        {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}">下一页</a>
        {% endif %}
    {% endif %}
    </div>
<!--</ul>-->
{% endblock %}

typeidea/themes/bootstrap/templates/blog/clslist2.html
{% extends "./base.html" %}

{% block title %}
    {% if tag %}
    <!-- 标签页：{{ tag.name }} -->
    标签页：{{ sidebars }}
    {% elif category %}
    分类页：{{ category.naame }}
    {% endif %}
{% endblock%}

{% block main %}
{{ sidebars }}
<ul>
    {% for post in post_list %}
    <li>
        <!-- <a href="/post/{{ post.id }}.html">{{ post.title }}</a> -->
        <a href="{% url 'post-detail' post.id%}">{{ post.title }}</a>
        <div>
            <span>作者：{{ post.owner.username }}</span>
            <span>分类：{{ post.category.name }}</span>
        </div>
        <p>{{ post.desc }}</p>
    </li>
    {% endfor %}
    {% if page_obj %}
        {% if page_obj.has_previous %}
            <a href="?page={{ page_obj.previous_page_number }}">上一页</a>
        {% endif %}
        Page {{ page_obj.number }} of {{ paginator.num_pages }}.
        {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}">下一页</a>
        {% endif %}
    {% endif %}
</ul>
{% endblock %}

typeidea/themes/bootstrap/templates/blog/detail.html
<h1>detail</h1>
{% if post %}
<hi>{{ post.title }}</hi>
<div>
    <span>分类：{{ post.category.name }}</span>
    <span>作者：{{ post.owner.username }}</span>
</div>
<p>{{ post.content }}</p>
{% endif %}

typeidea/themes/bootstrap/templates/blog/links.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>links</title>
</head>
<body>
    <h1>links</h1>
    {{ name }}
</body>
</html>

typeidea/themes/bootstrap/templates/blog/list-bk.html
<!DOCTYPE html>
<html lang="zh-cn">
<head>
    <meta charset="UTF-8">
    <title>typeidea 博客系统</title>
</head>
<body>
<!-- 导航 -->
<div>顶部导航：
    {% for cate in navs %}
    <a href="/category/{{ cate.id }}/">{{ cate.name }}</a>
    {% endfor %}
</div>


<!-- 侧边栏 -->
<div>侧边栏：
    {% for sidebar in sidebars %}
    <a href="/tag/{{ sidebar.id }}/">{{ sidebar.title }}</a>
    {% endfor %}
</div>

{% if tag %}
标签页：{{ tag.name }}
{% endif %}

{% if category %}
分类页：{{ category.name }}
{% endif %}

<ul>
    {% for post in post_list %}
    <li>
        <a href="/post/{{ post.id }}.html">{{ post.title }}</a>
        <div>
            <span>作者：{{ post.owner.username }}</span>
            <span>分类：{{ post.category.name }}</span>
        </div>
        <p>{{ post.desc }}</p>
    </li>
    {% endfor %}
</ul>

<!-- 导航 -->
<div>底部导航：
    {% for cate in categories %}
    <a href="/category/{{ cate.id }}/">{{ cate.name }}</a>
    {% endfor %}
</div>

</body>
</html>

typeidea/themes/bootstrap/templates/blog/list.html
{% extends "./base.html" %}

{% block title %}
    {% if tag %}
    标签页：{{ tag.name }}
    {% elif category %}
    分类页：{{ category.naame }}
    {% endif %}
{% endblock%}

{% block main %}
<ul>
    {% for post in post_list %}
    <li>
        <!-- <a href="/post/{{ post.id }}.html">{{ post.title }}</a> -->
        <a href="{% url 'post-detail' post.id%}">{{ post.title }}</a>
        <div>
            <span>作者：{{ post.owner.username }}</span>
            <span>分类：{{ post.category.name }}</span>
        </div>
        <p>{{ post.desc }}</p>
    </li>
    {% endfor %}
</ul>
{% endblock %}

typeidea/themes/bootstrap/templates/blog/result.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>评论结果页</title>
    <style>
        body {TEXT-ALIGN: center;}
        .result {
            text-aalign: center;
            width: 40%;
            margin: auto;
        }
        .errorlist {color: red;}
        ul li {
            list-style-type: None;
        }
    </style>
</head>
<body>
    <div class="result">
        {% if succeed %}
            评论成功!
            <a href="{{ target }}">返回</a>
        {% else %}
            <ul class="errorlist">
                {% for field, message in form.errors.items %}
                    <li>{{ message }}</li>
                {% endfor %}
            </ul>
            <a href="javascript:window.history.back();">返回</a>
        {% endif %}
    </div>
</body>
</html>