Q_and_A/django_app/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url

from myweb.views import question, test, thumbs, answer, SearchView

urlpatterns = [
    path('', question.as_view(), name='index'),
    path('question/<int:pk>/thumbs-up', thumbs, name='thumbs'),
    path('answer/', answer, name='answer'),
    path('test/', test, name='test'),
    path('admin/', admin.site.urls),
    url(r'^search/$', SearchView.as_view(), name='search'),
]

Q_and_A/myweb/models.py
from django.db import models
from django.contrib.auth.models import User


# 提问
class Questions(models.Model):
    STATUS_NORMAL = 0
    STATUS_CLOSE = 1
    STATUS_ITEM = (
        (STATUS_NORMAL, "正常"),
        (STATUS_CLOSE, "关闭"),
    )

    title = models.CharField(max_length=100, verbose_name="问题")
    content = models.TextField(verbose_name="详细描述")
    datetime = models.DateTimeField(verbose_name="时间", auto_now_add=True)
    status = models.PositiveIntegerField(verbose_name="状态", default=STATUS_NORMAL, choices=STATUS_ITEM)
    owner = models.ForeignKey(User, verbose_name="提问者", on_delete=models.SET_NULL, blank=True, null=True)
    thumbs_up = models.IntegerField(verbose_name="点赞", default=0)
    comments = models.IntegerField(verbose_name="评论", default=0)

    def __str__(self):
        return self.title

    def get_all(self):
        return self.objects.all()

    class Meta:
        verbose_name = verbose_name_plural = "问题清单"


# 回答
class Answer(models.Model):
    owner = models.ForeignKey(User, verbose_name="响应者", on_delete=models.SET_NULL, null=True, blank=True)
    question = models.ForeignKey(Questions, on_delete=models.SET_NULL, null=True, blank=True)
    content = models.TextField(verbose_name="回答")
    datetime = models.DateTimeField(auto_now_add=True, verbose_name="时间")
    ip_address = models.CharField(max_length=10, verbose_name="IP地址")

    def __str__(self):
        return self.content

    class Meta:
        verbose_name = verbose_name_plural = "回答列表"

Q_and_A/myweb/forms.py
from django import forms
from .models import Questions, Answer


class AnswerForm(forms.ModelForm):

    content = forms.CharField(
        label="回答",
        widget=forms.widgets.Textarea(
            attrs={'class': 'form-control col-md-10'}
        )
    )

    class Meta:
        model = Answer
        fields = (
            'question', 'content', 'owner'
        )


class QuestionsForm(forms.ModelForm):
    title = forms.CharField(
        label="标题",
        max_length=100,
        widget=forms.widgets.Input(
            attrs={'type': "text", 'class': 'form-control col-md-10', 'placeholder': "请输入标题"}
        )
    )

    content = forms.CharField(
        label="内容",
        widget=forms.widgets.Textarea(
            attrs={'rows': 6, 'cols': 30, 'class': 'form-control col-md-10'}
        )
    )

    class Meta:
        model = Questions
        fields = (
            'title', 'content'
        )

Q_and_A/myweb/views.py
from django.shortcuts import render, render_to_response, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from django.views.generic import ListView, DetailView
from django.contrib.auth.models import User

from myweb.models import Questions, Answer
from myweb.forms import QuestionsForm, AnswerForm


def get_user(request):
    """
    判断用户是否登录，登录成功返回的是用户对象，否则返回访问者。
    """
    user = request.user
    if isinstance(user, User):
    # if request.user.is_authenticated():
        return user
    else:
        return get_object_or_404(User, username='visitor')


class question(ListView):
    model = Questions
    paginate_by = 5
    context_object_name = 'questions'
    template_name = 'index.html'

    def get(self, request, *args, **kwargs):
        super().get(request, *args, **kwargs)
        # user = get_user(request)
        context = self.get_context_data(**kwargs)
        # context.update({'user': {'id': user.id, 'name': user.username, }})
        context.update({'question_number': self.get_queryset().count()})
        return render(request, 'index.html', context=context)

    def get_context_data(self, **kwargs):
        """ 传递问题表单进行渲染 """
        context = super().get_context_data(**kwargs)
        context.update({'questions_form': QuestionsForm})
        context.update({'answer_form': AnswerForm})
        return context

    def get_queryset(self):
        """ 按时间倒序 """
        queryset = super().get_queryset()
        return queryset.order_by('-datetime')

    def post(self, request):
        form = QuestionsForm(request.POST)
        if form.is_valid():
            cleaned_data = form.cleaned_data
            qst = Questions()
            qst.title = cleaned_data['title']
            qst.content = cleaned_data['content']
            qst.owner = get_user(request)
            qst.save()
        return HttpResponseRedirect(reverse('index'))


def answer(request):
    form = AnswerForm(request.POST)
    if form.is_valid():
        cleaned_data = form.cleaned_data
        ans = Answer()
        ans.content = cleaned_data['content']
        ans.owner = get_user(request)
        ans.question = cleaned_data['question']
        ans.save()
        print(get_user(request))
        print('saved')
    else:
        print('is not valid.')
    return HttpResponseRedirect(reverse('index'))


def thumbs(request, pk):
    qst = get_object_or_404(Questions, id=pk)
    qst.thumbs_up += 1
    qst.save()
    return HttpResponseRedirect(reverse('index'))


def test(request):
    return render(request, 'test.html')


class SearchView(ListView):
    def get_context_data(self):
        keyword = self.request.GET.get('keyword')
        context = super().get_queryset()
        context.update({'keyword': keyword })
        return context

    def get_queryset(self):
        return super().get_queryset()

Q_and_A/myweb/templates/base.html
<!DOCTYPE html>
<html lang="zh-CN">
<head>
    {% load staticfiles %}
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- 上述3个meta标签*必须*放在最前面，任何其他内容都*必须*跟随其后！ -->
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="../../favicon.ico">
    
    <title>你问我答</title>

    <!-- Bootstrap core CSS -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <script src="{% static 'js/jquery.min.js' %}"></script>
    <script srr="{% static 'js/bootstrap.min.js' %}"></script>

<!--	<link rel="stylesheet" href="https://cdn.staticfile.org/twitter-bootstrap/3.3.7/css/bootstrap.min.css">-->
<!--	<script src="https://cdn.staticfile.org/jquery/2.1.1/jquery.min.js"></script>-->
<!--	<script src="https://cdn.staticfile.org/twitter-bootstrap/3.3.7/js/bootstrap.min.js"></script>-->


    <!-- 自定义CSS-->
    <link href="{% static 'css/my.css' %}" type="text/css" rel="stylesheet">

</head>

<body>
    <div class="blog-masthead">
      <div class="container">
        <nav class="blog-nav nav navbar-nav ">
          <a class="blog-nav-item active" href="#">最新问答</a>
          <a class="blog-nav-item" href="#">热门话题</a>
          <a class="blog-nav-item" href="#">朋友圈</a>
          <a class="blog-nav-item" href="#">About</a>
        </nav>
        <nav >
            <form class="form-inline" action="/search/" method="GET">
                <input class="form-control" type="search" name="keyword" placeholder="Search"
                       aria-label="Search" value="{{ keyword }}">
                <button class="btn btn-outline-success" type="submit">搜索</button>
            </form>
        </nav>
        {% if request.user.is_authenticated %}
        <nav class="blog-nav nav navbar-nav navbar-right">
          <a class="blog-nav-item" href="admin/">{{ request.user }}</a>
        </nav>
        {% else %}
        <nav class="blog-nav nav navbar-nav navbar-right">
          <a class="blog-nav-item" href="#">注册</a>
          <a class="blog-nav-item" href="admin/">登录</a>
        </nav>
        {% endif %}
      </div>
    </div>

    <div class="container blog-panel">
      <div class="blog-header">
        <h1 class="blog-title">你问我答</h1>
        <p class="lead blog-description">这是一个自由应答的空间，这里有{{ question_number }}个问题，快来找到你感兴趣的话题，跟大家聊聊吧。</p>
      </div>
      <div class="pager">
        <button class="btn btn-primary btn-lg" data-toggle="modal" data-target="#myQuestion">
            开始提问
        </button>
      </div>
    {% block questions %}
    {% endblock %}
    </div>

    <!-- 模态框（Modal） -->
    <div class="modal fade" id="myQuestion" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">
                        &times;
                    </button>
                    <h4 class="modal-title" id="myModalLabel">
                        您的问题是
                    </h4>
                </div>
                <form class="form-horizontal" role="questions_form" action="/" method="POST">
                    {% csrf_token %}
                    <div class="modal-body">
                        <div class="form-group">
                            {% load myfunc %}
                            {{ questions_form.title|label_with_classes:'col-md-2 contal-label' }}
                            <div class="col-md-10">
                            {{ questions_form.title }}
                            </div>
                            {{ questions_form.content|label_with_classes:'col-md-2 contal-label' }}
                            <div class="col-md-10">
                            {{ questions_form.content }}
                            </div>
                        </div>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-default" data-dismiss="modal">
                            关闭
                        </button>
                        <button type="submit" class="btn btn-primary">
                            提交
                        </button>
                    </div>
                </form>
            </div><!-- /.modal-content -->
        </div><!-- /.modal -->
    </div>

    <footer class="blog-footer">
      <p>Blog template built for <a href="http://getbootstrap.com">Bootstrap</a> by <a href="https://twitter.com/mdo">@mdo</a>.</p>
      <p>
        <a href="#">Back to top</a>
      </p>
    </footer>

</body>

</html>

Q_and_A/myweb/templates/index-bk.html
{% extends 'base.html' %}

{% block questions %}
    <!-- 提问内容 -->
    <div class="row blog-panel">
      <ul class="col-md-12 col-xs-12">
        {% for qst in questions %}
        <li>
            <div class="blog-post">
                <h5 class="blog-post-title"><span>{{ qst.owner.username }}</span>问：<span> {{ qst.title }} </span></h5>
                <p><span> {{ qst.content }} </span></p>
                <div class="col-md-offset-11 col-md-2 col-xs-offset-11 col-xs-2">
                    <a href="question/{{ qst.id }}/thumbs-up"><span class="glyphicon glyphicon-thumbs-up"></span>{{ qst.thumbs_up }}</a>&nbsp
                    <a href="#"><span class="glyphicon glyphicon-new-window"></span></a>&nbsp
                    <a href="#"><span class="glyphicon glyphicon-comment" data-toggle="modal" data-target="#myModal" onclick="Values('{{ qst.id }}')" ></span></a>&nbsp
                </div>
            </div>
        </li>
        {% endfor %}
      </ul>
    </div>


    <!-- 模态框（Modal） -->
    <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">
                        &times;
                    </button>
                    <h4 class="modal-title" id="myModalLabel">
                        您的回答是
                    </h4>
                </div>
                <form class="form-horizontal" role="answer_form" action="answer/" method="POST">
                    {% csrf_token %}
                    <div class="modal-body">
                        <div class="form-group">
                            <input type="text" name="dateId" id="id" value="" />
                        </div>
                        <div class="form-group">
                            {% load myfunc %}
                            {{ answer_form.content|label_with_classes:'col-md-2 contal-label' }}
                            <div class="col-md-10">
                            {{ answer_form.question }}
                            {{ answer_form.content }}
                            </div>
                        </div>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-default" data-dismiss="modal">
                            关闭
                        </button>
                        <button type="submit" class="btn btn-primary">
                            提交
                        </button>
                    </div>
                </form>
            </div><!-- /.modal-content -->
        </div><!-- /.modal -->
    </div>

    <!-- 传递参数到模态框 -->
    <script type="text/javascript">
       $(function(){
            $('#myModal').modal("hide");
       });
       function Values(ID){
             $('#id_question').val(ID);
       }
    </script>

    <!-- 分页栏 -->
    <nav>
        <ul class="pager">
        {% if page_obj %}
            {% if page_obj.has_previous %}
                <li><a href="?page={{ page_obj.previous_page_number }}">上一页</a></li>
            {% endif %}
            {% if page_obj.has_next %}
                <li><a href="?page={{ page_obj.next_page_number }}">下一页</a></li>
            {% endif %}
        {% endif %}
        </ul>
    </nav>

{% endblock %}

Q_and_A/myweb/templates/index.html
{% extends 'base.html' %}

{% block questions %}
    <!-- 提问内容 -->
    <div class="row blog-panel">
      <ul class="col-md-12 col-xs-12">
        {% for qst in questions %}
        <li>
            <div class="blog-post">
                <h5 class="blog-post-title"><span>{{ qst.owner.username }}</span>问：<span> {{ qst.title }} </span></h5>
                <p><span> {{ qst.content }} </span></p>
                <div class="col-md-offset-11 col-md-2 col-xs-offset-11 col-xs-2">
                    <a href="question/{{ qst.id }}/thumbs-up"><span class="glyphicon glyphicon-thumbs-up"></span>{{ qst.thumbs_up }}</a>&nbsp
                    <a href="#"><span class="glyphicon glyphicon-new-window"></span></a>&nbsp
                    <a href="#"><span class="glyphicon glyphicon-comment" data-toggle="modal" data-target="#myModal" onclick="Values('{{ qst.id }}')" ></span></a>&nbsp
                </div>
            </div>
        </li>
        {% endfor %}
      </ul>
    </div>


    <!-- 模态框（Modal） -->
    <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">
                        &times;
                    </button>
                    <h4 class="modal-title" id="myModalLabel">
                        您的回答是
                    </h4>
                </div>
                <form class="form-horizontal" role="answer_form" action="answer/" method="POST">
                    {% csrf_token %}
                    <div class="modal-body">
                        <div class="form-group">
                            <input type="hidden" name="dateId" id="id" value="" />
                        </div>
                        <div class="form-group">
                            {% load myfunc %}

                            {{ answer_form.content|label_with_classes:'col-md-2 contal-label' }}
                            <div class="col-md-10">
                            {{ answer_form.content }}
                            {{ answer_form.question }}
                            </div>

                        </div>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-default" data-dismiss="modal">
                            关闭
                        </button>
                        <button type="submit" class="btn btn-primary">
                            提交
                        </button>
                    </div>
                </form>
            </div><!-- /.modal-content -->
        </div><!-- /.modal -->
    </div>

    <!-- 传递参数到模态框 -->
    <script type="text/javascript">
       $(function(){
            $('#myModal').modal("hide");
       });
       function Values(ID){
       <!--  给回答表单的问题标签付值，并且隐藏问题标签  -->
             $('#id_question').val(ID);
             document.getElementById('id_question').style.visibility='hidden';
       }
    </script>

    <!-- 分页栏 -->
    <nav>
        <ul class="pager">
        {% if page_obj %}
            {% if page_obj.has_previous %}
                <li><a href="?page={{ page_obj.previous_page_number }}">上一页</a></li>
            {% endif %}
            {% if page_obj.has_next %}
                <li><a href="?page={{ page_obj.next_page_number }}">下一页</a></li>
            {% endif %}
        {% endif %}
        </ul>
    </nav>

{% endblock %}

Q_and_A/myweb/templates/test.html
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<title>Bootstrap 实例 - 模态框（Modal）插件事件</title>
	<link rel="stylesheet" href="https://cdn.staticfile.org/twitter-bootstrap/3.3.7/css/bootstrap.min.css">
	<script src="https://cdn.staticfile.org/jquery/2.1.1/jquery.min.js"></script>
	<script src="https://cdn.staticfile.org/twitter-bootstrap/3.3.7/js/bootstrap.min.js"></script>
</head>
<body>

<h2>模态框（Modal）插件事件</h2>
<!-- 按钮触发模态框 -->
<button class="btn btn-primary btn-lg" data-toggle="modal" data-target="#myModal" onclick="values(2)">
	开始演示模态框
</button>
<!-- 模态框（Modal） -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal" aria-hidden="true">×
				</button>
				<h4 class="modal-title" id="myModalLabel">
					模态框（Modal）标题
				</h4>
			</div>
			<div class="modal-body">
				点击关闭按钮检查事件功能。
				<input type="hidden" name="dateId" id="dateId" value="" />
			</div>
			<div class="modal-footer">
				<button type="button" class="btn btn-default" data-dismiss="modal">
					关闭
				</button>
				<button type="button" class="btn btn-primary">
					提交更改
				</button>
			</div>
		</div><!-- /.modal-content -->
	</div><!-- /.modal-dialog -->
</div><!-- /.modal -->
<script>
   $(function () { $('#myModal').modal('hide')});
</script>
<script>
   $(function(){
        $('.myModal').modal("hide");
   });
   function values(ID){
        alert('嗨！'+ ID)
         $('#dateId').val(ID);
   }
</script>

</body>
</html>

Q_and_A/myweb/templates/test2.html
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<title>Bootstrap 实例 - 模态框（Modal）插件</title>
	<link rel="stylesheet" href="https://cdn.staticfile.org/twitter-bootstrap/3.3.7/css/bootstrap.min.css">
	<script src="https://cdn.staticfile.org/jquery/2.1.1/jquery.min.js"></script>
	<script src="https://cdn.staticfile.org/twitter-bootstrap/3.3.7/js/bootstrap.min.js"></script>
</head>
<body>

<h2>创建模态框（Modal）</h2>
<!-- 按钮触发模态框 -->
<button class="btn btn-primary btn-lg" data-toggle="modal" data-target="#myModal" onclick="values(1)">
	开始演示模态框参数传递
</button>
<!-- 模态框（Modal） -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal" aria-hidden="true">
					&times;
				</button>
				<h4 class="modal-title" id="myModalLabel">
					模态框（Modal）标题
				</h4>
			</div>
			<div class="modal-body">
				在这里添加一些文本
				<input type="hidden" name="dateId" id="dateId" value="" />
				<div class="planel_boxs">
					 <div class="row">
						 <div class="row_line col-md-6 col-sm-6 col-xs-12">
							 <label>单号：</label>
							 <input type="text" class="form-controls content" id="dataId2">
						 </div>
						 <div class="row_line col-md-6 col-sm-6 col-xs-12">
							 <label>名称：</label>
							 <input type="text" class="form-controls identify">
						 </div>
					</div>
				</div>
			</div>
			<div class="modal-footer">
				<button type="button" class="btn btn-default" data-dismiss="modal">关闭</button>
				<button type="submit" class="btn btn-primary">保存</button>
			</div>
		</div><!-- /.modal-content -->
	</div><!-- /.modal -->
</div>
<script type="text/javascript">
    $(function(){
        $('.myModal').modal("hide");
    });
    function values(ID){
         $('#dateId').val(ID);
    }
</script>
</body>
</html>